### ISSUE TITLE
NumberFormatException when trying to set stop without number

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-alexa#28]
After initial setup, I asked "Alexa, ask OneBusAway to set my stop", and got the below error log:

~~~
DEBUG request - Received successful response: 200, AWS Request ID: F54DKEBP8SP37I2HLOBMCGUELJVV4KQNSO5AEMVJF66Q9ASUAAJG

DEBUG DefaultListableBeanFactory - Returning cached instance of singleton bean 'authedSpeechlet'

DEBUG ObaUserClient - Instantiating ObaUserClient with obaBaseUrl http://api.tampa.onebusaway.org/api/

DEBUG AnonSpeechlet - Stop number string received: null

ERROR MainSpeechlet - Intent exception: null

ERROR MainSpeechlet - Backtrace:

[Ljava.lang.StackTraceElement;@27c20538

null: java.lang.NumberFormatException java.lang.NumberFormatException: 
null at java.lang.Integer.parseInt(Integer.java:542)
at java.lang.Integer.valueOf(Integer.java:766) 
at org.onebusaway.alexa.AnonSpeechlet.onIntent(AnonSpeechlet.java:137) 
at org.onebusaway.alexa.AuthedSpeechlet.onIntent(AuthedSpeechlet.java:71) 
at org.onebusaway.alexa.MainSpeechlet.onIntent(MainSpeechlet.java:45) 
at com.amazon.speech.speechlet.SpeechletRequestDispatcher.dispatchSpeechletCall(SpeechletRequestDispatcher.java:63) 
at com.amazon.speech.speechlet.SpeechletRequestHandler.handleSpeechletCall(SpeechletRequestHandler.java:69) 
at com.amazon.speech.speechlet.lambda.SpeechletRequestStreamHandler.handleRequest(SpeechletRequestStreamHandler.java:81)

END RequestId: e7de0214-e3ff-11e5-9f53-e5c625172e24
~~~

**Comment by barbeau** [comment]
Fixed via https://github.com/OneBusAway/onebusaway-alexa/pull/38.
